// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulpbkjyczwqhtwlqnafj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscGJranljendxaHR3bHFuYWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTA2OTMsImV4cCI6MjA4ODU2NjY5M30.iYuofv0EvxViY_eQMTrpjslj-p04XnarC1zQZy5AkyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});